-- ============================================
-- INDEXES FOR MDHSYS SCHEMA
-- ============================================

-- Asset Read-Only Indexes
create index MDHSYS.IDX_ACT_RO_ASSET on MDHSYS.ACT_RO_ASSET(RAT_CP_CODE, RAT_AST_CODE);
create index MDHSYS.IDX_ACT_RO_BALANCE on MDHSYS.ACT_RO_BALANCE(RPT_CP_CODE, RPT_COA3_CODE);
create index MDHSYS.IDX_ACT_RO_BNK_STAT on MDHSYS.ACT_RO_BNK_STAT(BNK_CP_CODE, BNK_COA3_CODE);
create index MDHSYS.IDX_ACT_RO_CHQ_HIS on MDHSYS.ACT_RO_CHQ_HIS(RCH_CP_CODE, RCH_COA3_CODE);
create index MDHSYS.IDX_ACT_RO_FNCL_RPT on MDHSYS.ACT_RO_FNCL_RPT(FRP_CP_CODE, FRP_PRG_CODE);
create index MDHSYS.IDX_ACT_RO_LEDGER on MDHSYS.ACT_RO_LEDGER(RPT_CP_CODE, RPT_COA3_CODE, RPT_DATE);

-- Asset Detail Indexes
create index MDHSYS.IDX_ACT_SD_ADD_ASSET on MDHSYS.ACT_SD_ADD_ASSET(DAA_CP_CODE, DAA_AST_CODE);
create index MDHSYS.IDX_ACT_SD_ADEPT on MDHSYS.ACT_SD_ADEPT(DAD_CP_CODE, DAD_AST_CODE);
create index MDHSYS.IDX_ACT_SD_ASSET on MDHSYS.ACT_SD_ASSET(DAT_CP_CODE, DAT_AST_CODE);
create index MDHSYS.IDX_ACT_SD_ASSET_TRACKING on MDHSYS.ACT_SD_ASSET_TRACKING(DTR_CP_CODE, DTR_AST_CODE);

-- Asset Master Indexes
create index MDHSYS.IDX_ACT_SM_ASSET on MDHSYS.ACT_SM_ASSET(AST_CP_CODE, AST_CODE);
create index MDHSYS.IDX_ACT_SM_ASSET_STATUS on MDHSYS.ACT_SM_ASSET(AST_STATUS, AST_CP_CODE);

-- Accounting Setup Indexes
create index MDHSYS.IDX_ACT_SD_BANK on MDHSYS.ACT_SD_BANK(DBK_CP_CODE, DBK_COA3_CODE);
create index MDHSYS.IDX_ACT_SD_BUDGET on MDHSYS.ACT_SD_BUDGET(DBG_CP_CODE, DBG_FYR_FM);
create index MDHSYS.IDX_ACT_SD_COA_LEVEL3 on MDHSYS.ACT_SD_COA_LEVEL3(COA3_CP_CODE, COA3_CODE);
create index MDHSYS.IDX_ACT_SD_COA_OPNBAL on MDHSYS.ACT_SD_COA_OPNBAL(DCO_CP_CODE, DCO_FYR_FM);
create index MDHSYS.IDX_ACT_SD_VOUCHER on MDHSYS.ACT_SD_VOUCHER(DDV_CP_CODE, DDV_MDV_CODE);

-- Hospital Indexes
create index MDHSYS.IDX_PATIENT_MASTER on MDHSYS.PATIENT_MASTER(PATIENT_ID, CONTACT_NO);
create index MDHSYS.IDX_ADMISSION on MDHSYS.ADMISSION(PATIENT_ID, ADMISSION_DATE);
create index MDHSYS.IDX_BILLING on MDHSYS.BILLING(PATIENT_ID, BILL_DATE);
create index MDHSYS.IDX_BILLING_DETAILS on MDHSYS.BILLING_DETAILS(BILL_ID);
create index MDHSYS.IDX_AUDIT_LOG on MDHSYS.AUDIT_LOG(TABLE_NAME, LOG_DATE);

commit;