-- ============================================
-- APEX 26 - COMPLETE HOSPITAL ERP SYSTEM
-- Admin Module + All Hospital Modules
-- ============================================

-- ============================================
-- ADMIN MODULE - User Management
-- ============================================

CREATE TABLE MDHSYS.ADMIN_USERS (
    USER_ID VARCHAR2(8) PRIMARY KEY,
    USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    FULL_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE,
    MOBILE VARCHAR2(15),
    ROLE_ID VARCHAR2(10),
    DEPARTMENT VARCHAR2(50),
    STATUS VARCHAR2(1) DEFAULT 'A',
    LAST_LOGIN DATE,
    LOGIN_ATTEMPTS NUMBER DEFAULT 0,
    LOCKED_UNTIL DATE,
    PASSWORD_CHANGED_DATE DATE,
    CREATED_DATE DATE DEFAULT SYSDATE,
    CREATED_BY VARCHAR2(30),
    UPDATED_DATE DATE,
    UPDATED_BY VARCHAR2(30),
    CONSTRAINT PK_ADMIN_USERS PRIMARY KEY (USER_ID)
);

CREATE TABLE MDHSYS.USER_ROLES (
    ROLE_ID VARCHAR2(10) PRIMARY KEY,
    ROLE_NAME VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    PERMISSIONS CLOB,
    STATUS VARCHAR2(1) DEFAULT 'A',
    CREATED_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE MDHSYS.AUDIT_TRAIL (
    AUDIT_ID NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(8),
    ACTION VARCHAR2(50),
    TABLE_NAME VARCHAR2(50),
    RECORD_ID VARCHAR2(50),
    OLD_VALUE CLOB,
    NEW_VALUE CLOB,
    IP_ADDRESS VARCHAR2(50),
    AUDIT_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (USER_ID) REFERENCES MDHSYS.ADMIN_USERS(USER_ID)
);

CREATE TABLE MDHSYS.SYSTEM_CONFIG (
    CONFIG_ID VARCHAR2(20) PRIMARY KEY,
    CONFIG_NAME VARCHAR2(100) NOT NULL,
    CONFIG_VALUE VARCHAR2(4000),
    DATA_TYPE VARCHAR2(20),
    DESCRIPTION VARCHAR2(500),
    UPDATED_DATE DATE DEFAULT SYSDATE
);

-- ============================================
-- HOSPITAL MODULE - Patient Management
-- ============================================

CREATE TABLE MDHSYS.HOSPITAL_UNITS (
    UNIT_ID VARCHAR2(8) PRIMARY KEY,
    UNIT_NAME VARCHAR2(100) NOT NULL,
    UNIT_CODE VARCHAR2(10) UNIQUE,
    UNIT_TYPE VARCHAR2(30),
    STATUS VARCHAR2(1) DEFAULT 'A',
    CREATED_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE MDHSYS.PATIENT_CATEGORIES (
    CATEGORY_ID VARCHAR2(8) PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(50) NOT NULL,
    CATEGORY_CODE VARCHAR2(10) UNIQUE,
    STATUS VARCHAR2(1) DEFAULT 'A'
);

CREATE TABLE MDHSYS.PATIENT_MASTER_EXTENDED (
    PATIENT_ID VARCHAR2(10) PRIMARY KEY,
    PATIENT_NAME VARCHAR2(100) NOT NULL,
    GENDER VARCHAR2(1),
    DOB DATE,
    AGE NUMBER(3),
    BLOOD_GROUP VARCHAR2(5),
    CONTACT_NO VARCHAR2(15),
    ALTERNATE_CONTACT VARCHAR2(15),
    EMAIL VARCHAR2(100),
    ADDRESS VARCHAR2(500),
    CITY VARCHAR2(50),
    STATE VARCHAR2(50),
    COUNTRY VARCHAR2(50),
    PINCODE VARCHAR2(10),
    EMERGENCY_CONTACT VARCHAR2(100),
    EMERGENCY_PHONE VARCHAR2(15),
    CATEGORY_ID VARCHAR2(8),
    INSURANCE_ID VARCHAR2(20),
    INSURANCE_PROVIDER VARCHAR2(100),
    PATIENT_PHOTO BLOB,
    PATIENT_STATUS VARCHAR2(1) DEFAULT 'A',
    CREATED_DATE DATE DEFAULT SYSDATE,
    CREATED_BY VARCHAR2(30),
    UPDATED_DATE DATE,
    UPDATED_BY VARCHAR2(30),
    FOREIGN KEY (CATEGORY_ID) REFERENCES MDHSYS.PATIENT_CATEGORIES(CATEGORY_ID)
);

CREATE TABLE MDHSYS.PATIENT_HISTORY (
    HISTORY_ID NUMBER PRIMARY KEY,
    PATIENT_ID VARCHAR2(10),
    VISIT_DATE DATE,
    CHIEF_COMPLAINT VARCHAR2(500),
    DIAGNOSIS VARCHAR2(500),
    TREATMENT_PLAN VARCHAR2(2000),
    NOTES CLOB,
    CREATED_BY VARCHAR2(30),
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (PATIENT_ID) REFERENCES MDHSYS.PATIENT_MASTER_EXTENDED(PATIENT_ID)
);

-- ============================================
-- OPD MODULE - Out Patient Department
-- ============================================

CREATE TABLE MDHSYS.OPD_REGISTRATION (
    OPD_REG_ID VARCHAR2(15) PRIMARY KEY,
    PATIENT_ID VARCHAR2(10),
    REGISTRATION_DATE DATE DEFAULT SYSDATE,
    UNIT_ID VARCHAR2(8),
    DOCTOR_ID VARCHAR2(8),
    APPOINTMENT_TIME VARCHAR2(10),
    CHIEF_COMPLAINT VARCHAR2(500),
    NOTES CLOB,
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    TOKEN_NUMBER NUMBER,
    PRIORITY VARCHAR2(20),
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (PATIENT_ID) REFERENCES MDHSYS.PATIENT_MASTER_EXTENDED(PATIENT_ID),
    FOREIGN KEY (UNIT_ID) REFERENCES MDHSYS.HOSPITAL_UNITS(UNIT_ID)
);

CREATE TABLE MDHSYS.OPD_CONSULTATION (
    CONSULTATION_ID VARCHAR2(15) PRIMARY KEY,
    OPD_REG_ID VARCHAR2(15),
    DOCTOR_ID VARCHAR2(8),
    CONSULTATION_DATE DATE,
    CONSULTATION_TIME VARCHAR2(10),
    DIAGNOSIS VARCHAR2(500),
    VITAL_SIGNS CLOB,
    PHYSICAL_EXAMINATION CLOB,
    INVESTIGATION_REQUIRED VARCHAR2(4000),
    ADVICE VARCHAR2(2000),
    FOLLOW_UP_REQUIRED VARCHAR2(1),
    FOLLOW_UP_DATE DATE,
    CONSULTATION_CHARGES NUMBER(10,2),
    STATUS VARCHAR2(20),
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (OPD_REG_ID) REFERENCES MDHSYS.OPD_REGISTRATION(OPD_REG_ID)
);

CREATE TABLE MDHSYS.OPD_PRESCRIPTION (
    PRESCRIPTION_ID VARCHAR2(15) PRIMARY KEY,
    CONSULTATION_ID VARCHAR2(15),
    MEDICINE_ID VARCHAR2(10),
    MEDICINE_NAME VARCHAR2(100),
    DOSAGE VARCHAR2(50),
    FREQUENCY VARCHAR2(50),
    DURATION VARCHAR2(50),
    INSTRUCTIONS VARCHAR2(500),
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2),
    TOTAL_PRICE NUMBER(10,2),
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (CONSULTATION_ID) REFERENCES MDHSYS.OPD_CONSULTATION(CONSULTATION_ID)
);

-- ============================================
-- IPD MODULE - In Patient Department
-- ============================================

CREATE TABLE MDHSYS.WARD_MASTER (
    WARD_ID VARCHAR2(8) PRIMARY KEY,
    WARD_NAME VARCHAR2(50) NOT NULL,
    WARD_CODE VARCHAR2(10) UNIQUE,
    WARD_TYPE VARCHAR2(30),
    TOTAL_BEDS NUMBER,
    OCCUPIED_BEDS NUMBER DEFAULT 0,
    STATUS VARCHAR2(1) DEFAULT 'A'
);

CREATE TABLE MDHSYS.BED_MASTER (
    BED_ID VARCHAR2(10) PRIMARY KEY,
    WARD_ID VARCHAR2(8),
    BED_NUMBER VARCHAR2(10),
    BED_TYPE VARCHAR2(30),
    OCCUPANCY_STATUS VARCHAR2(20) DEFAULT 'AVAILABLE',
    LAST_OCCUPIED_DATE DATE,
    STATUS VARCHAR2(1) DEFAULT 'A',
    FOREIGN KEY (WARD_ID) REFERENCES MDHSYS.WARD_MASTER(WARD_ID)
);

CREATE TABLE MDHSYS.ADMISSION_EXTENDED (
    ADMISSION_ID VARCHAR2(15) PRIMARY KEY,
    PATIENT_ID VARCHAR2(10),
    WARD_ID VARCHAR2(8),
    BED_ID VARCHAR2(10),
    ADMISSION_DATE DATE,
    ADMISSION_TIME VARCHAR2(10),
    ADMISSION_TYPE VARCHAR2(30),
    DOCTOR_ID VARCHAR2(8),
    CHIEF_COMPLAINT VARCHAR2(500),
    CLINICAL_HISTORY CLOB,
    DISCHARGE_DATE DATE,
    DISCHARGE_TIME VARCHAR2(10),
    DISCHARGE_SUMMARY CLOB,
    DISCHARGE_DIAGNOSIS VARCHAR2(500),
    STATUS VARCHAR2(20) DEFAULT 'ADMITTED',
    TOTAL_DAYS NUMBER,
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (PATIENT_ID) REFERENCES MDHSYS.PATIENT_MASTER_EXTENDED(PATIENT_ID),
    FOREIGN KEY (WARD_ID) REFERENCES MDHSYS.WARD_MASTER(WARD_ID),
    FOREIGN KEY (BED_ID) REFERENCES MDHSYS.BED_MASTER(BED_ID)
);

CREATE TABLE MDHSYS.MEDICAL_RECORDS (
    RECORD_ID VARCHAR2(15) PRIMARY KEY,
    ADMISSION_ID VARCHAR2(15),
    RECORD_DATE DATE,
    RECORD_TIME VARCHAR2(10),
    VITAL_SIGNS CLOB,
    CLINICAL_NOTES CLOB,
    MEDICATIONS_GIVEN CLOB,
    CREATED_BY VARCHAR2(30),
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (ADMISSION_ID) REFERENCES MDHSYS.ADMISSION_EXTENDED(ADMISSION_ID)
);

-- ============================================
-- PHARMACY MODULE
-- ============================================

CREATE TABLE MDHSYS.PHARMACY_ITEMS (
    ITEM_ID VARCHAR2(10) PRIMARY KEY,
    MEDICINE_NAME VARCHAR2(100) NOT NULL,
    MEDICINE_CODE VARCHAR2(20) UNIQUE,
    GENERIC_NAME VARCHAR2(100),
    MANUFACTURER VARCHAR2(100),
    CATEGORY VARCHAR2(50),
    UNIT VARCHAR2(20),
    STRENGTH VARCHAR2(50),
    REORDER_LEVEL NUMBER,
    CURRENT_STOCK NUMBER DEFAULT 0,
    UNIT_PRICE NUMBER(10,2),
    STATUS VARCHAR2(1) DEFAULT 'A',
    CREATED_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE MDHSYS.PHARMACY_STOCK (
    STOCK_ID VARCHAR2(15) PRIMARY KEY,
    ITEM_ID VARCHAR2(10),
    BATCH_NUMBER VARCHAR2(50),
    PURCHASE_DATE DATE,
    EXPIRY_DATE DATE,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2),
    SUPPLIER_ID VARCHAR2(10),
    STATUS VARCHAR2(1) DEFAULT 'A',
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (ITEM_ID) REFERENCES MDHSYS.PHARMACY_ITEMS(ITEM_ID)
);

CREATE TABLE MDHSYS.PHARMACY_SALES (
    SALE_ID VARCHAR2(15) PRIMARY KEY,
    SALE_DATE DATE,
    ITEM_ID VARCHAR2(10),
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2),
    TOTAL_PRICE NUMBER(10,2),
    SOLD_TO VARCHAR2(100),
    BILL_REF VARCHAR2(20),
    STATUS VARCHAR2(20) DEFAULT 'COMPLETED',
    CREATED_BY VARCHAR2(30),
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (ITEM_ID) REFERENCES MDHSYS.PHARMACY_ITEMS(ITEM_ID)
);

-- ============================================
-- SALARY & PAYROLL MODULE
-- ============================================

CREATE TABLE MDHSYS.EMPLOYEE_MASTER (
    EMP_ID VARCHAR2(8) PRIMARY KEY,
    EMP_CODE VARCHAR2(20) UNIQUE,
    EMP_NAME VARCHAR2(100) NOT NULL,
    DESIGNATION VARCHAR2(50),
    DEPARTMENT VARCHAR2(50),
    DOB DATE,
    GENDER VARCHAR2(1),
    CONTACT_NO VARCHAR2(15),
    EMAIL VARCHAR2(100),
    ADDRESS VARCHAR2(500),
    CITY VARCHAR2(50),
    BANK_ACCOUNT_NO VARCHAR2(20),
    BANK_NAME VARCHAR2(100),
    IFSC_CODE VARCHAR2(20),
    SALARY_GRADE VARCHAR2(10),
    BASIC_SALARY NUMBER(12,2),
    STATUS VARCHAR2(1) DEFAULT 'A',
    JOIN_DATE DATE,
    CREATED_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE MDHSYS.SALARY_STRUCTURE (
    SALARY_ID VARCHAR2(15) PRIMARY KEY,
    EMP_ID VARCHAR2(8),
    FINANCIAL_YEAR VARCHAR2(9),
    BASIC_SALARY NUMBER(12,2),
    HRA NUMBER(12,2),
    DA NUMBER(12,2),
    ALLOWANCES NUMBER(12,2),
    DEDUCTIONS NUMBER(12,2),
    GROSS_SALARY NUMBER(12,2),
    NET_SALARY NUMBER(12,2),
    EFFECTIVE_DATE DATE,
    STATUS VARCHAR2(1) DEFAULT 'A',
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (EMP_ID) REFERENCES MDHSYS.EMPLOYEE_MASTER(EMP_ID)
);

CREATE TABLE MDHSYS.SALARY_PAYMENT (
    PAYMENT_ID VARCHAR2(15) PRIMARY KEY,
    EMP_ID VARCHAR2(8),
    PAYMENT_MONTH VARCHAR2(7),
    BASIC_SALARY NUMBER(12,2),
    ALLOWANCES NUMBER(12,2),
    DEDUCTIONS NUMBER(12,2),
    GROSS_SALARY NUMBER(12,2),
    NET_SALARY NUMBER(12,2),
    PAYMENT_DATE DATE,
    PAYMENT_METHOD VARCHAR2(20),
    REFERENCE_NO VARCHAR2(30),
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (EMP_ID) REFERENCES MDHSYS.EMPLOYEE_MASTER(EMP_ID)
);

CREATE TABLE MDHSYS.ATTENDANCE (
    ATTENDANCE_ID VARCHAR2(15) PRIMARY KEY,
    EMP_ID VARCHAR2(8),
    ATTENDANCE_DATE DATE,
    IN_TIME VARCHAR2(10),
    OUT_TIME VARCHAR2(10),
    STATUS VARCHAR2(20),
    NOTES VARCHAR2(500),
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (EMP_ID) REFERENCES MDHSYS.EMPLOYEE_MASTER(EMP_ID)
);

CREATE TABLE MDHSYS.LEAVE_MASTER (
    LEAVE_ID VARCHAR2(15) PRIMARY KEY,
    EMP_ID VARCHAR2(8),
    LEAVE_TYPE VARCHAR2(30),
    FROM_DATE DATE,
    TO_DATE DATE,
    NUMBER_OF_DAYS NUMBER,
    REASON VARCHAR2(500),
    APPROVAL_STATUS VARCHAR2(20) DEFAULT 'PENDING',
    APPROVED_BY VARCHAR2(8),
    APPROVAL_DATE DATE,
    APPROVED_REMARKS VARCHAR2(500),
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (EMP_ID) REFERENCES MDHSYS.EMPLOYEE_MASTER(EMP_ID)
);

-- ============================================
-- PURCHASE MODULE
-- ============================================

CREATE TABLE MDHSYS.VENDOR_MASTER (
    VENDOR_ID VARCHAR2(10) PRIMARY KEY,
    VENDOR_NAME VARCHAR2(100) NOT NULL,
    VENDOR_CODE VARCHAR2(20) UNIQUE,
    CONTACT_PERSON VARCHAR2(100),
    CONTACT_NO VARCHAR2(15),
    EMAIL VARCHAR2(100),
    CITY VARCHAR2(50),
    STATE VARCHAR2(50),
    COUNTRY VARCHAR2(50),
    PINCODE VARCHAR2(10),
    PAN_GST VARCHAR2(20),
    BANK_DETAILS CLOB,
    CREDIT_LIMIT NUMBER(12,2),
    PAYMENT_TERMS VARCHAR2(100),
    STATUS VARCHAR2(1) DEFAULT 'A',
    CREATED_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE MDHSYS.PURCHASE_ORDER (
    PO_ID VARCHAR2(15) PRIMARY KEY,
    PO_NUMBER VARCHAR2(30) UNIQUE,
    PO_DATE DATE,
    VENDOR_ID VARCHAR2(10),
    DELIVERY_DATE DATE,
    TOTAL_AMOUNT NUMBER(12,2),
    TAX_AMOUNT NUMBER(12,2),
    GRAND_TOTAL NUMBER(12,2),
    STATUS VARCHAR2(20) DEFAULT 'DRAFT',
    APPROVED_BY VARCHAR2(8),
    APPROVED_DATE DATE,
    CREATED_BY VARCHAR2(30),
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (VENDOR_ID) REFERENCES MDHSYS.VENDOR_MASTER(VENDOR_ID)
);

CREATE TABLE MDHSYS.PO_ITEMS (
    PO_ITEM_ID VARCHAR2(15) PRIMARY KEY,
    PO_ID VARCHAR2(15),
    ITEM_ID VARCHAR2(10),
    ITEM_NAME VARCHAR2(100),
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2),
    TOTAL_PRICE NUMBER(10,2),
    UOM VARCHAR2(10),
    NOTES VARCHAR2(500),
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (PO_ID) REFERENCES MDHSYS.PURCHASE_ORDER(PO_ID)
);

CREATE TABLE MDHSYS.GOODS_RECEIPT (
    GR_ID VARCHAR2(15) PRIMARY KEY,
    GR_NUMBER VARCHAR2(30) UNIQUE,
    PO_ID VARCHAR2(15),
    GR_DATE DATE,
    RECEIVED_BY VARCHAR2(30),
    TOTAL_ITEMS NUMBER,
    REMARKS CLOB,
    STATUS VARCHAR2(20) DEFAULT 'COMPLETED',
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (PO_ID) REFERENCES MDHSYS.PURCHASE_ORDER(PO_ID)
);

-- ============================================
-- INVENTORY MODULE
-- ============================================

CREATE TABLE MDHSYS.INVENTORY_ITEMS (
    INV_ITEM_ID VARCHAR2(10) PRIMARY KEY,
    ITEM_NAME VARCHAR2(100) NOT NULL,
    ITEM_CODE VARCHAR2(20) UNIQUE,
    CATEGORY VARCHAR2(50),
    UNIT VARCHAR2(20),
    REORDER_LEVEL NUMBER,
    CURRENT_STOCK NUMBER DEFAULT 0,
    UNIT_PRICE NUMBER(10,2),
    SUPPLIER_ID VARCHAR2(10),
    STATUS VARCHAR2(1) DEFAULT 'A',
    CREATED_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE MDHSYS.INVENTORY_TRANSACTIONS (
    TXN_ID VARCHAR2(15) PRIMARY KEY,
    TXN_DATE DATE,
    INV_ITEM_ID VARCHAR2(10),
    TXN_TYPE VARCHAR2(20),
    QUANTITY NUMBER,
    REFERENCE_ID VARCHAR2(20),
    REMARKS VARCHAR2(500),
    CREATED_BY VARCHAR2(30),
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (INV_ITEM_ID) REFERENCES MDHSYS.INVENTORY_ITEMS(INV_ITEM_ID)
);

CREATE TABLE MDHSYS.STOCK_VALUATION (
    VALUATION_ID VARCHAR2(15) PRIMARY KEY,
    INV_ITEM_ID VARCHAR2(10),
    VALUATION_DATE DATE,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2),
    TOTAL_VALUE NUMBER(12,2),
    VALUATION_METHOD VARCHAR2(20),
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (INV_ITEM_ID) REFERENCES MDHSYS.INVENTORY_ITEMS(INV_ITEM_ID)
);

-- ============================================
-- ACCOUNTS & FINANCE MODULE
-- ============================================

CREATE TABLE MDHSYS.CHART_OF_ACCOUNTS (
    COA_ID VARCHAR2(10) PRIMARY KEY,
    ACCOUNT_CODE VARCHAR2(20) UNIQUE NOT NULL,
    ACCOUNT_NAME VARCHAR2(100) NOT NULL,
    ACCOUNT_TYPE VARCHAR2(50),
    ACCOUNT_GROUP VARCHAR2(50),
    OPENING_BALANCE NUMBER(15,2),
    CURRENT_BALANCE NUMBER(15,2),
    STATUS VARCHAR2(1) DEFAULT 'A',
    CREATED_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE MDHSYS.JOURNAL_ENTRIES (
    JOURNAL_ID VARCHAR2(15) PRIMARY KEY,
    JOURNAL_DATE DATE,
    REFERENCE_NO VARCHAR2(30),
    DESCRIPTION VARCHAR2(500),
    TOTAL_DEBIT NUMBER(15,2),
    TOTAL_CREDIT NUMBER(15,2),
    STATUS VARCHAR2(20) DEFAULT 'DRAFT',
    APPROVED_BY VARCHAR2(8),
    APPROVED_DATE DATE,
    CREATED_BY VARCHAR2(30),
    CREATED_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE MDHSYS.JOURNAL_DETAILS (
    DETAIL_ID VARCHAR2(15) PRIMARY KEY,
    JOURNAL_ID VARCHAR2(15),
    COA_ID VARCHAR2(10),
    DEBIT_AMOUNT NUMBER(15,2),
    CREDIT_AMOUNT NUMBER(15,2),
    NARRATIVE VARCHAR2(500),
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (JOURNAL_ID) REFERENCES MDHSYS.JOURNAL_ENTRIES(JOURNAL_ID),
    FOREIGN KEY (COA_ID) REFERENCES MDHSYS.CHART_OF_ACCOUNTS(COA_ID)
);

CREATE TABLE MDHSYS.INVOICE_MASTER (
    INVOICE_ID VARCHAR2(15) PRIMARY KEY,
    INVOICE_NO VARCHAR2(30) UNIQUE,
    INVOICE_DATE DATE,
    BILL_TO VARCHAR2(100),
    PATIENT_ID VARCHAR2(10),
    ADMISSION_ID VARCHAR2(15),
    TOTAL_AMOUNT NUMBER(12,2),
    TAX_AMOUNT NUMBER(12,2),
    GRAND_TOTAL NUMBER(12,2),
    PAID_AMOUNT NUMBER(12,2) DEFAULT 0,
    BALANCE_AMOUNT NUMBER(12,2),
    STATUS VARCHAR2(20) DEFAULT 'DRAFT',
    CREATED_BY VARCHAR2(30),
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (PATIENT_ID) REFERENCES MDHSYS.PATIENT_MASTER_EXTENDED(PATIENT_ID)
);

CREATE TABLE MDHSYS.PAYMENT_RECEIPT (
    RECEIPT_ID VARCHAR2(15) PRIMARY KEY,
    RECEIPT_NO VARCHAR2(30) UNIQUE,
    INVOICE_ID VARCHAR2(15),
    PAYMENT_DATE DATE,
    PAYMENT_MODE VARCHAR2(30),
    AMOUNT NUMBER(12,2),
    CHEQUE_NO VARCHAR2(20),
    BANK_NAME VARCHAR2(100),
    REFERENCE_NO VARCHAR2(30),
    RECEIVED_BY VARCHAR2(30),
    STATUS VARCHAR2(20) DEFAULT 'COMPLETED',
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (INVOICE_ID) REFERENCES MDHSYS.INVOICE_MASTER(INVOICE_ID)
);

-- ============================================
-- LAB MODULE
-- ============================================

CREATE TABLE MDHSYS.LAB_TESTS (
    TEST_ID VARCHAR2(10) PRIMARY KEY,
    TEST_NAME VARCHAR2(100) NOT NULL,
    TEST_CODE VARCHAR2(20) UNIQUE,
    CATEGORY VARCHAR2(50),
    PRICE NUMBER(10,2),
    REFERENCE_RANGE VARCHAR2(500),
    TURNAROUND_TIME VARCHAR2(50),
    STATUS VARCHAR2(1) DEFAULT 'A',
    CREATED_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE MDHSYS.LAB_ORDERS (
    ORDER_ID VARCHAR2(15) PRIMARY KEY,
    ORDER_DATE DATE,
    PATIENT_ID VARCHAR2(10),
    ADMISSION_ID VARCHAR2(15),
    DOCTOR_ID VARCHAR2(8),
    TEST_ID VARCHAR2(10),
    SPECIMEN_ID VARCHAR2(20),
    COLLECTION_DATE DATE,
    COLLECTION_TIME VARCHAR2(10),
    PRIORITY VARCHAR2(20),
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (PATIENT_ID) REFERENCES MDHSYS.PATIENT_MASTER_EXTENDED(PATIENT_ID),
    FOREIGN KEY (TEST_ID) REFERENCES MDHSYS.LAB_TESTS(TEST_ID)
);

CREATE TABLE MDHSYS.LAB_RESULTS (
    RESULT_ID VARCHAR2(15) PRIMARY KEY,
    ORDER_ID VARCHAR2(15),
    TEST_ID VARCHAR2(10),
    RESULT_VALUE VARCHAR2(500),
    UNIT VARCHAR2(30),
    REFERENCE_RANGE VARCHAR2(500),
    ABNORMAL_FLAG VARCHAR2(1),
    RESULT_DATE DATE,
    TESTED_BY VARCHAR2(30),
    VERIFIED_BY VARCHAR2(30),
    VERIFICATION_DATE DATE,
    STATUS VARCHAR2(20) DEFAULT 'COMPLETED',
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (ORDER_ID) REFERENCES MDHSYS.LAB_ORDERS(ORDER_ID),
    FOREIGN KEY (TEST_ID) REFERENCES MDHSYS.LAB_TESTS(TEST_ID)
);

-- ============================================
-- DIAGNOSTIC MODULE
-- ============================================

CREATE TABLE MDHSYS.DIAGNOSTIC_TESTS (
    DIAG_TEST_ID VARCHAR2(10) PRIMARY KEY,
    TEST_NAME VARCHAR2(100) NOT NULL,
    TEST_CODE VARCHAR2(20) UNIQUE,
    CATEGORY VARCHAR2(50),
    MODALITY VARCHAR2(50),
    PRICE NUMBER(10,2),
    SLOT_DURATION NUMBER,
    STATUS VARCHAR2(1) DEFAULT 'A',
    CREATED_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE MDHSYS.DIAGNOSTIC_ORDERS (
    DIAG_ORDER_ID VARCHAR2(15) PRIMARY KEY,
    ORDER_DATE DATE,
    PATIENT_ID VARCHAR2(10),
    ADMISSION_ID VARCHAR2(15),
    DOCTOR_ID VARCHAR2(8),
    DIAG_TEST_ID VARCHAR2(10),
    SCHEDULED_DATE DATE,
    SCHEDULED_TIME VARCHAR2(10),
    TECHNICIAN_ID VARCHAR2(8),
    PRIORITY VARCHAR2(20),
    STATUS VARCHAR2(20) DEFAULT 'SCHEDULED',
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (PATIENT_ID) REFERENCES MDHSYS.PATIENT_MASTER_EXTENDED(PATIENT_ID),
    FOREIGN KEY (DIAG_TEST_ID) REFERENCES MDHSYS.DIAGNOSTIC_TESTS(DIAG_TEST_ID)
);

CREATE TABLE MDHSYS.DIAGNOSTIC_REPORTS (
    REPORT_ID VARCHAR2(15) PRIMARY KEY,
    DIAG_ORDER_ID VARCHAR2(15),
    REPORT_DATE DATE,
    FINDINGS CLOB,
    IMPRESSION CLOB,
    RECOMMENDATIONS VARCHAR2(2000),
    RADIOLOGIST_ID VARCHAR2(8),
    REPORT_FILE BLOB,
    STATUS VARCHAR2(20) DEFAULT 'COMPLETED',
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (DIAG_ORDER_ID) REFERENCES MDHSYS.DIAGNOSTIC_ORDERS(DIAG_ORDER_ID)
);

-- ============================================
-- ASSETS MANAGEMENT MODULE
-- ============================================

CREATE TABLE MDHSYS.ASSET_MASTER (
    ASSET_ID VARCHAR2(10) PRIMARY KEY,
    ASSET_CODE VARCHAR2(20) UNIQUE NOT NULL,
    ASSET_NAME VARCHAR2(100) NOT NULL,
    ASSET_TYPE VARCHAR2(50),
    CATEGORY VARCHAR2(50),
    PURCHASE_DATE DATE,
    PURCHASE_COST NUMBER(12,2),
    USEFUL_LIFE NUMBER,
    DEPRECIATION_RATE NUMBER(5,2),
    LOCATION VARCHAR2(100),
    CURRENT_VALUE NUMBER(12,2),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATED_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE MDHSYS.ASSET_DEPRECIATION (
    DEPRECIATION_ID VARCHAR2(15) PRIMARY KEY,
    ASSET_ID VARCHAR2(10),
    DEPRECIATION_MONTH VARCHAR2(7),
    DEPRECIATION_AMOUNT NUMBER(12,2),
    ACCUMULATED_DEPRECIATION NUMBER(12,2),
    NET_BOOK_VALUE NUMBER(12,2),
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (ASSET_ID) REFERENCES MDHSYS.ASSET_MASTER(ASSET_ID)
);

CREATE TABLE MDHSYS.ASSET_MAINTENANCE (
    MAINTENANCE_ID VARCHAR2(15) PRIMARY KEY,
    ASSET_ID VARCHAR2(10),
    MAINTENANCE_DATE DATE,
    MAINTENANCE_TYPE VARCHAR2(50),
    COST NUMBER(10,2),
    DESCRIPTION CLOB,
    VENDOR VARCHAR2(100),
    NEXT_MAINTENANCE DATE,
    STATUS VARCHAR2(20),
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (ASSET_ID) REFERENCES MDHSYS.ASSET_MASTER(ASSET_ID)
);

-- ============================================
-- AMBULANCE SERVICES MODULE
-- ============================================

CREATE TABLE MDHSYS.AMBULANCE_MASTER (
    AMBULANCE_ID VARCHAR2(10) PRIMARY KEY,
    AMBULANCE_REG_NO VARCHAR2(20) UNIQUE,
    AMBULANCE_TYPE VARCHAR2(30),
    VEHICLE_MAKE VARCHAR2(50),
    VEHICLE_MODEL VARCHAR2(50),
    MANUFACTURING_YEAR NUMBER(4),
    DRIVER_NAME VARCHAR2(100),
    DRIVER_LICENSE VARCHAR2(20),
    DRIVER_CONTACT VARCHAR2(15),
    LOCATION VARCHAR2(100),
    STATUS VARCHAR2(20) DEFAULT 'AVAILABLE',
    CREATED_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE MDHSYS.AMBULANCE_CALLS (
    CALL_ID VARCHAR2(15) PRIMARY KEY,
    CALL_DATE DATE,
    CALL_TIME VARCHAR2(10),
    CALLER_NAME VARCHAR2(100),
    CALLER_CONTACT VARCHAR2(15),
    PICKUP_LOCATION VARCHAR2(500),
    DROPOFF_LOCATION VARCHAR2(500),
    PATIENT_NAME VARCHAR2(100),
    PATIENT_CONDITION VARCHAR2(500),
    AMBULANCE_ID VARCHAR2(10),
    DISPATCHED_TIME VARCHAR2(10),
    PICKUP_TIME VARCHAR2(10),
    DROPOFF_TIME VARCHAR2(10),
    DISTANCE_KM NUMBER(5,2),
    CHARGE_AMOUNT NUMBER(10,2),
    STATUS VARCHAR2(20),
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (AMBULANCE_ID) REFERENCES MDHSYS.AMBULANCE_MASTER(AMBULANCE_ID)
);

-- ============================================
-- NOTIFICATIONS & COMMUNICATION MODULE
-- ============================================

CREATE TABLE MDHSYS.NOTIFICATION_TEMPLATES (
    TEMPLATE_ID VARCHAR2(15) PRIMARY KEY,
    TEMPLATE_NAME VARCHAR2(100) NOT NULL,
    TEMPLATE_TYPE VARCHAR2(20),
    CONTENT CLOB,
    VARIABLES CLOB,
    STATUS VARCHAR2(1) DEFAULT 'A',
    CREATED_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE MDHSYS.SMS_LOGS (
    SMS_ID VARCHAR2(15) PRIMARY KEY,
    SMS_DATE DATE,
    RECIPIENT_NO VARCHAR2(15),
    MESSAGE_CONTENT VARCHAR2(4000),
    TEMPLATE_ID VARCHAR2(15),
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    SENT_DATE DATE,
    DELIVERY_STATUS VARCHAR2(20),
    CREATED_BY VARCHAR2(30),
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (TEMPLATE_ID) REFERENCES MDHSYS.NOTIFICATION_TEMPLATES(TEMPLATE_ID)
);

CREATE TABLE MDHSYS.WHATSAPP_LOGS (
    WHATSAPP_ID VARCHAR2(15) PRIMARY KEY,
    WHATSAPP_DATE DATE,
    RECIPIENT_NO VARCHAR2(15),
    MESSAGE_CONTENT VARCHAR2(4000),
    MEDIA_URL VARCHAR2(500),
    TEMPLATE_ID VARCHAR2(15),
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    SENT_DATE DATE,
    DELIVERY_STATUS VARCHAR2(20),
    CREATED_BY VARCHAR2(30),
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (TEMPLATE_ID) REFERENCES MDHSYS.NOTIFICATION_TEMPLATES(TEMPLATE_ID)
);

CREATE TABLE MDHSYS.SYSTEM_NOTIFICATIONS (
    NOTIFICATION_ID VARCHAR2(15) PRIMARY KEY,
    NOTIFICATION_DATE DATE,
    USER_ID VARCHAR2(8),
    NOTIFICATION_TYPE VARCHAR2(50),
    TITLE VARCHAR2(200),
    MESSAGE CLOB,
    LINK VARCHAR2(500),
    IS_READ VARCHAR2(1) DEFAULT 'N',
    READ_DATE DATE,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATED_DATE DATE DEFAULT SYSDATE
);

-- ============================================
-- GROUP CHAT & MESSAGING MODULE
-- ============================================

CREATE TABLE MDHSYS.CHAT_GROUPS (
    GROUP_ID VARCHAR2(15) PRIMARY KEY,
    GROUP_NAME VARCHAR2(100) NOT NULL,
    GROUP_TYPE VARCHAR2(30),
    GROUP_DESCRIPTION VARCHAR2(500),
    CREATED_BY VARCHAR2(8),
    CREATED_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(1) DEFAULT 'A'
);

CREATE TABLE MDHSYS.GROUP_MEMBERS (
    MEMBER_ID VARCHAR2(15) PRIMARY KEY,
    GROUP_ID VARCHAR2(15),
    USER_ID VARCHAR2(8),
    ROLE VARCHAR2(20),
    JOINED_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(1) DEFAULT 'A',
    FOREIGN KEY (GROUP_ID) REFERENCES MDHSYS.CHAT_GROUPS(GROUP_ID)
);

CREATE TABLE MDHSYS.GROUP_MESSAGES (
    MESSAGE_ID VARCHAR2(15) PRIMARY KEY,
    GROUP_ID VARCHAR2(15),
    USER_ID VARCHAR2(8),
    MESSAGE_TEXT CLOB,
    MEDIA_URL VARCHAR2(500),
    MESSAGE_DATE DATE,
    MESSAGE_TIME VARCHAR2(10),
    IS_READ VARCHAR2(1) DEFAULT 'N',
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (GROUP_ID) REFERENCES MDHSYS.CHAT_GROUPS(GROUP_ID),
    FOREIGN KEY (USER_ID) REFERENCES MDHSYS.ADMIN_USERS(USER_ID)
);

CREATE TABLE MDHSYS.PRIVATE_MESSAGES (
    PRIVATE_MSG_ID VARCHAR2(15) PRIMARY KEY,
    SENDER_ID VARCHAR2(8),
    RECEIVER_ID VARCHAR2(8),
    MESSAGE_TEXT CLOB,
    MEDIA_URL VARCHAR2(500),
    MESSAGE_DATE DATE,
    MESSAGE_TIME VARCHAR2(10),
    IS_READ VARCHAR2(1) DEFAULT 'N',
    READ_DATE DATE,
    STATUS VARCHAR2(20) DEFAULT 'SENT',
    CREATED_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (SENDER_ID) REFERENCES MDHSYS.ADMIN_USERS(USER_ID),
    FOREIGN KEY (RECEIVER_ID) REFERENCES MDHSYS.ADMIN_USERS(USER_ID)
);

-- ============================================
-- CREATE INDEXES FOR PERFORMANCE
-- ============================================

CREATE INDEX IDX_PATIENT_MASTER ON MDHSYS.PATIENT_MASTER_EXTENDED(PATIENT_ID, CONTACT_NO);
CREATE INDEX IDX_OPD_REGISTRATION ON MDHSYS.OPD_REGISTRATION(PATIENT_ID, REGISTRATION_DATE);
CREATE INDEX IDX_ADMISSION_EXTENDED ON MDHSYS.ADMISSION_EXTENDED(PATIENT_ID, ADMISSION_DATE);
CREATE INDEX IDX_INVOICE_MASTER ON MDHSYS.INVOICE_MASTER(PATIENT_ID, INVOICE_DATE);
CREATE INDEX IDX_SALARY_PAYMENT ON MDHSYS.SALARY_PAYMENT(EMP_ID, PAYMENT_MONTH);
CREATE INDEX IDX_JOURNAL_ENTRIES ON MDHSYS.JOURNAL_ENTRIES(JOURNAL_DATE, STATUS);
CREATE INDEX IDX_LAB_ORDERS ON MDHSYS.LAB_ORDERS(PATIENT_ID, ORDER_DATE);
CREATE INDEX IDX_DIAGNOSTIC_ORDERS ON MDHSYS.DIAGNOSTIC_ORDERS(PATIENT_ID, ORDER_DATE);
CREATE INDEX IDX_SMS_LOGS ON MDHSYS.SMS_LOGS(SMS_DATE, STATUS);
CREATE INDEX IDX_GROUP_MESSAGES ON MDHSYS.GROUP_MESSAGES(GROUP_ID, MESSAGE_DATE);
CREATE INDEX IDX_PRIVATE_MESSAGES ON MDHSYS.PRIVATE_MESSAGES(SENDER_ID, RECEIVER_ID, MESSAGE_DATE);

COMMIT;

DBMS_OUTPUT.PUT_LINE('✅ COMPLETE HOSPITAL ERP SYSTEM CREATED SUCCESSFULLY!');
DBMS_OUTPUT.PUT_LINE('Total Tables: 80+');
DBMS_OUTPUT.PUT_LINE('Total Modules: 15');
